package;

#if macro
import haxe.macro.Context;
import sys.FileSystem;
import sys.io.File;
import MacroDetector.TestableFunction;
import TestModel.GenerationResult;
import TestModel.GeneratorConfig;

using StringTools;

class GeneratorCore {
	public static inline var GENERATED_STAMP:String = "@generated by Vision test generator";

	public static function generateAll(config:GeneratorConfig):GenerationResult {
		var sourceDir = FileSystem.absolutePath(config.source);
		var destDir = FileSystem.absolutePath(config.destination);
		ensureDirectory(destDir);
		writeSupportFiles(destDir);

		var result:GenerationResult = {
			testClasses: [],
			suites: [],
			generatedFiles: [],
			skippedFiles: [],
			protectedFiles: [],
			failed: []
		};

		var files = config.regenerateAll ? readFileStructure(sourceDir) : [];
		for (file in files) {
			if (shouldSkipSource(file, config.exclude)) continue;

			var className = file.split("/").pop().replace(".hx", "");
			var outputFile = destDir + "/" + className + "Test.hx";
			var sourceClassPath = extractClassPath(file, sourceDir);
			var outputExists = FileSystem.exists(outputFile);
			var provenance = outputExists && !isGeneratedFile(outputFile) ? "legacy_mixed" : "generated";

			if (outputExists && !isGeneratedFile(outputFile) && !canWriteGeneratedFile(outputFile, config.overwrite)) {
				var existingSuite = TestPlanner.planSuite(sourceClassPath, outputFile, [], provenance);
				RunnerPolicy.applyLifecycle(existingSuite);
				result.suites.push(existingSuite);
				result.testClasses.push(existingSuite.testClassName);
				Sys.println('Skipping: $file (existing non-generated output cataloged as $provenance)');
				result.skippedFiles.push(outputFile);
				continue;
			}

			var testables:Array<TestableFunction> = [];
			try {
				testables = MacroDetector.detectClass(sourceClassPath);
			} catch (e:Dynamic) {
				var message = 'Could not analyze $sourceClassPath: $e';
				Sys.println('  INFO: ' + message);
				result.failed.push(message);
			}

			if ((testables == null || testables.length == 0) && !outputExists) {
				Sys.println('  INFO: No testable members found in $sourceClassPath');
				continue;
			}

			var suite = TestPlanner.planSuite(sourceClassPath, outputFile, testables, provenance);
			RunnerPolicy.applyLifecycle(suite);
			result.suites.push(suite);
			result.testClasses.push(suite.testClassName);

			if (testables == null || testables.length == 0) {
				continue;
			}

			Sys.println('Generating: $sourceClassPath -> $outputFile');
			File.saveContent(outputFile, TestEmitter.emitSuite(suite));
			result.generatedFiles.push(outputFile);
		}

		writeGeneratedSuites(destDir, RunnerPolicy.runnableClasses(result.suites));
		writeRunnerIfSafe(config, result);
		writeCatalog(config, result);
		return result;
	}

	public static function generateTestFile(sourceClassPath:String, outputPath:String, ?fixturesPath:String):Bool {
		var testables = MacroDetector.detectClass(sourceClassPath);
		if (testables == null || testables.length == 0) {
			Sys.println('INFO: No testable members found in $sourceClassPath');
			return false;
		}
		if (FileSystem.exists(outputPath) && !canWriteGeneratedFile(outputPath, true)) {
			Sys.println('INFO: Refusing to overwrite non-generated test file $outputPath');
			return false;
		}
		var suite = TestPlanner.planSuite(sourceClassPath, outputPath, testables, "generated");
		ensureDirectory(haxe.io.Path.directory(outputPath));
		File.saveContent(outputPath, TestEmitter.emitSuite(suite));
		return true;
	}

	static function shouldSkipSource(file:String, excludes:Array<String>):Bool {
		if (file.endsWith(".js.hx")) {
			Sys.println('Skipping: $file (js interface file)');
			return true;
		}
		for (exclude in excludes) {
			if (file.contains(exclude)) {
				Sys.println('Skipping: $file (excluded: $exclude)');
				return true;
			}
		}
		return false;
	}

	static function writeSupportFiles(destination:String):Void {
		var supportDir = destination + "/support";
		ensureDirectory(supportDir);
		var factoriesPath = supportDir + "/Factories.hx";
		if (!FileSystem.exists(factoriesPath) || isGeneratedFile(factoriesPath)) {
			File.saveContent(factoriesPath, TestEmitter.emitFactories());
		}

		var rootDir = haxe.io.Path.directory(destination);
		var reporterPath = rootDir + "/PrettyReporter.hx";
		if (!FileSystem.exists(reporterPath) || isGeneratedFile(reporterPath)) {
			File.saveContent(reporterPath, readGeneratorTemplate("PrettyReporter.hx"));
		}
	}

	static function readGeneratorTemplate(fileName:String):String {
		var candidates = [
			"generator/templates/" + fileName,
			"tests/generator/templates/" + fileName
		];
		for (path in candidates) {
			if (FileSystem.exists(path)) return File.getContent(path);
		}
		throw 'Missing generator template: $fileName';
	}

	static function writeGeneratedSuites(destination:String, testClasses:Array<String>):Void {
		var supportDir = destination + "/support";
		ensureDirectory(supportDir);
		var suitesPath = supportDir + "/GeneratedSuites.hx";
		File.saveContent(suitesPath, TestEmitter.emitGeneratedSuites(testClasses));
	}

	static function writeRunnerIfSafe(config:GeneratorConfig, result:GenerationResult):Void {
		if (config.testsToRunFile == null || config.testsToRunFile.length == 0) return;
		var runnerPath = FileSystem.absolutePath(config.testsToRunFile);
		if (!canWriteGeneratedFile(runnerPath, config.overwrite)) {
			Sys.println('  Runner protected (not generator-owned): $runnerPath');
			result.protectedFiles.push(runnerPath);
			return;
		}
		ensureDirectory(haxe.io.Path.directory(runnerPath));
		var mainClass = haxe.io.Path.withoutExtension(haxe.io.Path.withoutDirectory(runnerPath));
		File.saveContent(runnerPath, TestEmitter.emitRunner(result.testClasses, mainClass));
		result.generatedFiles.push(runnerPath);
	}

	static function writeCatalog(config:GeneratorConfig, result:GenerationResult):Void {
		var manifestPath = FileSystem.absolutePath(config.catalogFile != null && config.catalogFile.length > 0 ? config.catalogFile : "catalog/test-manifest.json");
		CatalogEmitter.writeManifest(manifestPath, result.suites, result);
		CatalogEmitter.writeHealthIfMissing(haxe.io.Path.directory(manifestPath) + "/test-health.json");
		CatalogEmitter.writeReport(haxe.io.Path.directory(manifestPath) + "/test-report.md", result.suites, result);
		Sys.println('  Test manifest: $manifestPath');
	}

	static function canWriteGeneratedFile(path:String, overwrite:Bool):Bool {
		if (!FileSystem.exists(path)) return true;
		if (isGeneratedFile(path)) return true;
		return false;
	}

	static function isGeneratedFile(path:String):Bool {
		if (!FileSystem.exists(path)) return false;
		try {
			return File.getContent(path).indexOf(GENERATED_STAMP) != -1;
		} catch (e:Dynamic) {
			return false;
		}
	}

	static function extractClassPath(filePath:String, sourceRoot:String):String {
		var normalizedFile = filePath.replace("\\", "/");
		var visionIndex = normalizedFile.indexOf("/vision/");
		if (visionIndex != -1) {
			var relative = normalizedFile.substr(visionIndex + 1);
			return relative.replace("/", ".").replace(".hx", "");
		}
		var parts = normalizedFile.split("/");
		return parts[parts.length - 1].replace(".hx", "");
	}

	static function readFileStructure(from:String):Array<String> {
		var files = FileSystem.readDirectory(from);
		var result:Array<String> = [];
		for (file in files) {
			var path = from + "/" + file;
			if (FileSystem.isDirectory(path)) {
				result = result.concat(readFileStructure(path));
			} else {
				result.push(path);
			}
		}
		return result;
	}

	static function ensureDirectory(path:String):Void {
		if (path == null || path.length == 0 || FileSystem.exists(path)) return;
		var parent = haxe.io.Path.directory(path);
		if (parent != null && parent.length > 0 && parent != path) ensureDirectory(parent);
		FileSystem.createDirectory(path);
	}
}
#end