package;

import MacroDetector.TestableKind;
import TestModel.PlannedSuite;
import TestModel.PlannedTestCase;

using StringTools;

class TestEmitter {
	public static function emitSuite(suite:PlannedSuite):String {
		var buf = new StringBuf();
		buf.add('// @generated by Vision test generator v' + TestPlanner.GENERATOR_VERSION + '\n');
		buf.add('// Do not edit this file directly; update generator inputs instead.\n');
		buf.add('package tests;\n\n');
		for (imp in collectImports(suite)) {
			buf.add('import ' + imp + ';\n');
		}
		buf.add('\n');
		buf.add('@:access(' + suite.sourceClassPath + ')\n');
		buf.add('@:visionGeneratorVersion("' + TestPlanner.GENERATOR_VERSION + '")\n');
		buf.add('@:visionProvenance(' + haxeString(suite.provenance) + ')\n');
		buf.add('@:visionMaturity(' + haxeString(suite.maturity) + ')\n');
		buf.add('@:visionLifecycle(' + haxeString(suite.lifecycle) + ')\n');
		buf.add('class ' + suite.testClassName + ' extends utest.Test {\n\n');
		for (testCase in suite.cases) {
			buf.add(emitCase(testCase));
			buf.add('\n');
		}
		buf.add('}\n');
		return buf.toString();
	}

	public static function emitRunner(testClasses:Array<String>, mainClass:String):String {
		var sorted = testClasses.copy();
		sorted.sort(function(a, b) return Reflect.compare(a, b));
		var buf = new StringBuf();
		buf.add('// @generated by Vision test generator v' + TestPlanner.GENERATOR_VERSION + '\n');
		buf.add('package;\n\n');
		buf.add('using StringTools;\n\n');
		buf.add('import utest.Runner;\n');
		buf.add('import PrettyReporter;\n');
		buf.add('import tests.*;\n\n');
		buf.add('#if nodejs\n');
		buf.add('import js.Node;\n');
		buf.add('#end\n\n');
		buf.add('class ' + mainClass + ' {\n');
		buf.add('\tstatic function main() {\n');
		buf.add('\t\tvar runner = new Runner();\n\n');
		buf.add('\t\tvar rawFilter:String = null;\n');
		buf.add('\t\t#if sys\n');
		buf.add('\t\trawFilter = Sys.getEnv("VISION_TESTS");\n');
		buf.add('\t\tif (rawFilter == null || rawFilter.trim().length == 0) rawFilter = Sys.getEnv("VISION_TEST_CLASSES");\n');
		buf.add('\t\t#elseif nodejs\n');
		buf.add('\t\tvar env = Node.process.env;\n');
		buf.add('\t\tif (env != null) {\n');
		buf.add('\t\t\trawFilter = env.get("VISION_TESTS");\n');
		buf.add('\t\t\tif (rawFilter == null || rawFilter.trim().length == 0) rawFilter = env.get("VISION_TEST_CLASSES");\n');
		buf.add('\t\t}\n');
		buf.add('\t\t#end\n\n');
		buf.add('\t\tvar args:Array<String> = [];\n');
		buf.add('\t\t#if sys\n');
		buf.add('\t\targs = Sys.args();\n');
		buf.add('\t\t#elseif nodejs\n');
		buf.add('\t\targs = Node.process.argv;\n');
		buf.add('\t\t#end\n');
		buf.add('\t\tfor (i in 0...args.length) {\n');
		buf.add('\t\t\tif (args[i] == "--tests" && i + 1 < args.length) {\n');
		buf.add('\t\t\t\trawFilter = args[i + 1];\n');
		buf.add('\t\t\t\tbreak;\n');
		buf.add('\t\t\t}\n');
		buf.add('\t\t}\n\n');
		buf.add('\t\tvar filter:Array<String> = [];\n');
		buf.add('\t\tif (rawFilter != null && rawFilter.trim().length > 0) {\n');
		buf.add('\t\t\tfor (part in rawFilter.split(",")) {\n');
		buf.add('\t\t\t\tvar name = part.trim();\n');
		buf.add('\t\t\t\tif (name.length > 0) filter.push(name);\n');
		buf.add('\t\t\t}\n');
		buf.add('\t\t}\n\n');
		buf.add('\t\tfunction includeTest(name:String):Bool {\n');
		buf.add('\t\t\treturn filter.length == 0 || filter.indexOf(name) != -1;\n');
		buf.add('\t\t}\n\n');
		for (cls in sorted) {
			buf.add('\t\tif (includeTest("' + cls + '")) runner.addCase(new ' + cls + '());\n');
		}
		buf.add('\n\t\tnew PrettyReporter(runner);\n');
		buf.add('\t\trunner.run();\n');
		buf.add('\t}\n');
		buf.add('}\n');
		return buf.toString();
	}

	public static function emitGeneratedSuites(testClasses:Array<String>):String {
		var sorted = testClasses.copy();
		sorted.sort(function(a, b) return Reflect.compare(a, b));
		var buf = new StringBuf();
		buf.add('// @generated by Vision test generator v' + TestPlanner.GENERATOR_VERSION + '\n');
		buf.add('package tests.support;\n\n');
		buf.add('import utest.Runner;\n');
		buf.add('import tests.*;\n\n');
		buf.add('class GeneratedSuites {\n');
		buf.add('\tpublic static function addCases(runner:Runner, includeTest:String->Bool):Void {\n');
		for (cls in sorted) {
			buf.add('\t\tif (includeTest("' + cls + '")) runner.addCase(new ' + cls + '());\n');
		}
		buf.add('\t}\n');
		buf.add('}\n');
		return buf.toString();
	}

	public static function emitFactories():String {
		var buf = new StringBuf();
		buf.add('// @generated by Vision test generator v' + TestPlanner.GENERATOR_VERSION + '\n');
		buf.add('package tests.support;\n\n');
		buf.add('import vision.ds.Color;\n');
		buf.add('import vision.ds.Image;\n\n');
		buf.add('class Factories {\n');
		buf.add('\tpublic static function blankImage(width:Int = 100, height:Int = 100, color:Color = 0x00000000):Image {\n');
		buf.add('\t\treturn new Image(width, height, color);\n');
		buf.add('\t}\n\n');
		buf.add('\tpublic static function blackImage(width:Int = 100, height:Int = 100):Image {\n');
		buf.add('\t\treturn new Image(width, height, 0xFF000000);\n');
		buf.add('\t}\n\n');
		buf.add('\tpublic static function gradientImage(width:Int = 100, height:Int = 100):Image {\n');
		buf.add('\t\tvar image = new Image(width, height);\n');
		buf.add('\t\tfor (y in 0...height) {\n');
		buf.add('\t\t\tfor (x in 0...width) {\n');
		buf.add('\t\t\t\tvar r = Std.int((x / width) * 255);\n');
		buf.add('\t\t\t\tvar g = Std.int((y / height) * 255);\n');
		buf.add('\t\t\t\tvar b = Std.int(((x + y) / (width + height)) * 255);\n');
		buf.add('\t\t\t\timage.setPixel(x, y, Color.fromRGBA(r, g, b, 255));\n');
		buf.add('\t\t\t}\n');
		buf.add('\t\t}\n');
		buf.add('\t\treturn image;\n');
		buf.add('\t}\n\n');
		buf.add('\tpublic static function checkerboardImage(width:Int = 8, height:Int = 8, cellSize:Int = 2):Image {\n');
		buf.add('\t\tvar image = new Image(width, height);\n');
		buf.add('\t\tfor (y in 0...height) {\n');
		buf.add('\t\t\tfor (x in 0...width) {\n');
		buf.add('\t\t\t\tvar light = (Std.int(x / cellSize) + Std.int(y / cellSize)) % 2 == 0;\n');
		buf.add('\t\t\t\timage.setPixel(x, y, light ? 0xFFFFFFFF : 0xFF000000);\n');
		buf.add('\t\t\t}\n');
		buf.add('\t\t}\n');
		buf.add('\t\treturn image;\n');
		buf.add('\t}\n');
		buf.add('\n\tpublic static function whiteLineImage(width:Int = 8, height:Int = 8):Image {\n');
		buf.add('\t\tvar image = new Image(width, height, 0xFF000000);\n');
		buf.add('\t\tvar y = height > 1 ? 1 : 0;\n');
		buf.add('\t\tfor (x in 0...width) image.setPixel(x, y, 0xFFFFFFFF);\n');
		buf.add('\t\treturn image;\n');
		buf.add('\t}\n');
		buf.add('}\n');
		return buf.toString();
	}

	static function emitCase(testCase:PlannedTestCase):String {
		var buf = new StringBuf();
		buf.add('\t@:visionTestId(' + haxeString(testCase.id) + ')\n');
		buf.add('\t@:visionProvenance(' + haxeString(testCase.provenance) + ')\n');
		buf.add('\t@:visionMaturity(' + haxeString(testCase.maturity) + ')\n');
		buf.add('\t@:visionLifecycle(' + haxeString(testCase.lifecycle) + ')\n');
		if (testCase.requirements.length > 0) {
			buf.add('\t@:visionRequires(' + testCase.requirements.map(haxeString).join(', ') + ')\n');
		}
		if (testCase.ignoreReason != null && testCase.ignoreReason.length > 0) {
			buf.add('\t@:Ignored(' + haxeString(testCase.ignoreReason) + ')\n');
		}
		var emittedMethodName = testCase.ignoreReason == null ? testCase.methodName : 'ignored_' + testCase.methodName;
		buf.add('\tfunction ' + emittedMethodName + '() {\n');
		for (param in testCase.parameters) {
			buf.add('\t\tvar ' + param.name + ' = ' + param.expression + ';\n');
		}
		var callTarget = testCase.functionInfo.isStatic ? testCase.functionInfo.packageName + '.' + testCase.functionInfo.className : 'instance';
		if (!testCase.functionInfo.isStatic) {
			if (testCase.functionInfo.instanceExpression != null && testCase.functionInfo.instanceExpression.length > 0) {
				buf.add('\t\tvar instance = ' + testCase.functionInfo.instanceExpression + ';\n');
			} else {
				var ctorArgs:Array<String> = [];
				for (param in testCase.constructorParameters) {
					var localName = 'ctor_' + param.name;
					buf.add('\t\tvar ' + localName + ' = ' + param.expression + ';\n');
					ctorArgs.push(localName);
				}
				buf.add('\t\tvar instance = new ' + testCase.functionInfo.packageName + '.' + testCase.functionInfo.className + '(' + ctorArgs.join(', ') + ');\n');
			}
		}

		var call = testCase.functionInfo.kind == TKProperty
			? callTarget + '.' + testCase.functionInfo.name
			: callTarget + '.' + testCase.functionInfo.name + '(' + testCase.parameters.map(param -> param.name).join(', ') + ')';
		emitAssertion(buf, call, testCase);
		buf.add('\t}\n');
		return buf.toString();
	}

	static function emitAssertion(buf:StringBuf, call:String, testCase:PlannedTestCase):Void {
		switch (testCase.assertion.strategy) {
			case "void_runs":
				buf.add('\t\t' + call + ';\n');
				buf.add('\t\tAssert.pass();\n');
			case "throws":
				buf.add('\t\tvar threw = false;\n');
				buf.add('\t\ttry {\n');
				buf.add('\t\t\t' + call + ';\n');
				buf.add('\t\t} catch (e:Dynamic) {\n');
				buf.add('\t\t\tthrew = true;\n');
				buf.add('\t\t}\n');
				buf.add('\t\tAssert.isTrue(threw);\n');
			case "image_structural":
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.notNull(result);\n');
				buf.add('\t\tAssert.isTrue(result.width > 0);\n');
				buf.add('\t\tAssert.isTrue(result.height > 0);\n');
				emitImageDimensionAssertions(buf, testCase);
			case "bytearray_structural":
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.notNull(result);\n');
				buf.add('\t\tAssert.isTrue(result.length > 0);\n');
			case "array_structural":
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.notNull(result);\n');
				buf.add('\t\tAssert.isTrue(result.length >= 0);\n');
			case "bool_structural":
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.isTrue(result == true || result == false);\n');
			case "float_structural":
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.isFalse(Math.isNaN(result));\n');
			case "is_nan":
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.isTrue(Math.isNaN(result));\n');
			case "nullable_access":
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.pass();\n');
			case "numeric_smoke":
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.notNull(result);\n');
			default:
				buf.add('\t\tvar result = ' + call + ';\n');
				buf.add('\t\tAssert.notNull(result);\n');
		}
	}

	static function emitImageDimensionAssertions(buf:StringBuf, testCase:PlannedTestCase):Void {
		var widthName = findParamName(testCase, ["width", "w"]);
		var heightName = findParamName(testCase, ["height", "h"]);
		if (widthName != null) buf.add('\t\tAssert.equals(' + widthName + ', result.width);\n');
		if (heightName != null) buf.add('\t\tAssert.equals(' + heightName + ', result.height);\n');
	}

	static function findParamName(testCase:PlannedTestCase, names:Array<String>):String {
		for (param in testCase.parameters) {
			var lowered = param.name.toLowerCase();
			if (names.indexOf(lowered) != -1) return param.name;
		}
		return null;
	}

	static function collectImports(suite:PlannedSuite):Array<String> {
		var seen = new Map<String, Bool>();
		var imports:Array<String> = [];
		addImport(imports, seen, 'utest.Assert');
		addImport(imports, seen, suite.sourceClassPath);
		var needsFactories = false;
		for (testCase in suite.cases) {
			for (param in testCase.parameters) {
				addVisionImport(imports, seen, param.type);
				if (param.expression != null && param.expression.indexOf('Factories.') != -1) needsFactories = true;
			}
			for (param in testCase.constructorParameters) {
				addVisionImport(imports, seen, param.type);
				if (param.expression != null && param.expression.indexOf('Factories.') != -1) needsFactories = true;
			}
		}
		if (needsFactories) addImport(imports, seen, 'tests.support.Factories');
		imports.sort(function(a, b) return Reflect.compare(a, b));
		return imports;
	}

	static function addVisionImport(imports:Array<String>, seen:Map<String, Bool>, typeName:String):Void {
		var visionTypes = [
			"Image" => "vision.ds.Image",
			"Color" => "vision.ds.Color",
			"Point2D" => "vision.ds.Point2D",
			"IntPoint2D" => "vision.ds.IntPoint2D",
			"Int16Point2D" => "vision.ds.Int16Point2D",
			"UInt16Point2D" => "vision.ds.UInt16Point2D",
			"Point3D" => "vision.ds.Point3D",
			"Line2D" => "vision.ds.Line2D",
			"Ray2D" => "vision.ds.Ray2D",
			"Pixel" => "vision.ds.Pixel",
			"ByteArray" => "vision.ds.ByteArray",
			"Kernel2D" => "vision.ds.Kernel2D",
			"Matrix2D" => "vision.ds.Matrix2D",
			"TransformationMatrix2D" => "vision.ds.TransformationMatrix2D",
			"Rectangle" => "vision.ds.Rectangle",
			"ImageView" => "vision.ds.ImageView",
			"Array2D" => "vision.ds.Array2D",
			"Queue" => "vision.ds.Queue",
			"Histogram" => "vision.ds.Histogram"
		];
		for (key => imp in visionTypes) {
			if (typeName != null && typeName.contains(key)) addImport(imports, seen, imp);
		}
	}

	static function addImport(imports:Array<String>, seen:Map<String, Bool>, imp:String):Void {
		if (!seen.exists(imp)) {
			seen.set(imp, true);
			imports.push(imp);
		}
	}

	static function haxeString(value:String):String {
		if (value == null) return '""';
		return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"';
	}
}